### ISSUE TITLE
Get Merger plots

### ISSUE THREAD

**Issue by Bvogel4** [Bvogel4/MorphologyMeasurements#3]
- [ ] Get merger axis ratios before and after each merger. 
- [x] plot recent mergers on a b/a vs c/a plot
- [x] plot recent mergers with b/a and c/a vs time 
- [ ] ~~plot of mergers vs non mergers in b/a vs c/a~~
- [ ] compile merger code into one function
- [x] define "recent"
- [x] Get merger trees working for Merians
- [ ] triaxiality plots

answer the questions
- if you remove merging galaxies do any of the trends differ? (i.e., do stars still follow DM? is that trend clearer w/o merging galaxies? What about triaxiality? is there less scatter if you remove merging galaxies?) 
-   What happens if you measure shape before the recent merger? Does that make stars follow DM better?  Can you create a track on the c/a, b/a plot just for the merging galaxies showing their evolution before, during and after the merger?  What does that plot tell us about DM and stellar shape through the process of a merger (all at r_eff).
- calculate the projected DM shapes like you do for the stars (using ellipsoid fitting)

**Comment by Bvogel4** [comment]
Can add shapes to tangos database, still need to refine smoothing and getting effective radius

**Comment by ferahmunshi** [comment]
plot of mergers vs non-mergers in b/a/c/a-- that will make a really crowded figure.  just make one for those which had a recent merger which may affect z=0-- so a merger in the previous 1-3 timesteps.  before that, things will have re-equilibrated because the time between timesteps is longer than the galaxy's dynamical time.

**Comment by ferahmunshi** [comment]
also look at recent mergers on the triaxiality plot.

**Comment by Bvogel4** [comment]
Main Merger fig for Merians




![Image](https://github.com/user-attachments/assets/06e18237-a173-423c-b9da-04d0dce11558)

**Comment by Bvogel4** [comment]
Get equivalent figures for Marvel + DCJL

**Comment by ferahmunshi** [comment]
put them all on one figure-- there are very few recent mergers in DCJL+marvel

**Comment by ferahmunshi** [comment]
Also, what is your interpretation here? How do recent mergers affect shape at z=0?  Also, are you sure these are all mergers that occurred within the last 3 timesteps?

**Comment by ferahmunshi** [comment]
tell me more about that one particular merger that has the drastic change in DM-- what z does this happen at? which halo is this? are you sure about such drastic change? have you made images at each of these timesteps to see visually what is going on? What is the mass ratio of this merger? you should have the size of the points correspond to mass ratio (like 1-1 would be a big point, but 4:1 would be a small point).

**Comment by Bvogel4** [comment]
Note: for Marvel Mergers, effective radius (reff) Failed to compute for earlier halos. I am currently using the value at z = 0. From what I have seen in the Merians, reff does not change much during a merger, or in the last 3 steps. Shape measurements are not super sensitive to specific radius with smoothing.
